routes/admin.php
<?php

// AJAX calls
Route::post('/dropdowns', 'AdminController@postDropdown');

// Admin Routes
Route::group(['prefix' => 'admin', 'middleware' => 'verified'], function() {
    // Index
    Route::get('/', 'AdminController@index')->name('admin');

    // Animal Routes
    Route::group(['prefix' => 'animals'], function () {
        Route::get('/', 'Animal\AnimalController@index')->name('admin.animals');
        Route::post('/fetch-all', 'Animal\AnimalController@postFetch');
        Route::post('/fetch', 'Animal\AnimalController@postFetchOne');
        Route::post('/create', 'Animal\AnimalController@postCreate');
        Route::post('/update', 'Animal\AnimalController@postUpdate');
        Route::post('/delete', 'Animal\AnimalController@postDelete');

        // Animal Species
        Route::group(['prefix' => 'species', 'middleware' => 'role:administrator|moderator'], function () {
            Route::get('/', 'Animal\AnimalSpeciesController@index')->name('admin.animals.species');
            Route::get('/fetch', 'Animal\AnimalSpeciesController@fetch')->name('admin.animals.species.fetch');
            Route::get('/create', 'Animal\AnimalSpeciesController@getCreate')->name('admin.animals.species.create');
            Route::post('/create', 'Animal\AnimalSpeciesController@postCreate');
            Route::get('/{id}', 'Animal\AnimalSpeciesController@getEdit')->name('admin.animals.species.edit');
            Route::post('/{id}', 'Animal\AnimalSpeciesController@postEdit');
            Route::get('/{id}/morphs', 'Animal\AnimalSpeciesController@getMorphs')->name('admin.animals.species.morphs');
            Route::post('/{id}/morphs', 'Animal\AnimalSpeciesController@postMorphs');


            // Animal Species: Morphs
            Route::group(['prefix' => 'morphs', 'middleware' => 'role:administrator|moderator'], function () {
                Route::post('/create', 'Animal\AnimalMorphController@postCreateMorph');
            });

            // Animal Species: Subspecies
            Route::group(['prefix' => 'subspecies', 'middleware' => 'role:administrator|moderator'], function () {
                Route::post('/create', 'Animal\AnimalSubspeciesController@postCreateSubspecies');
            });

            // Animal Species: Localities
            Route::group(['prefix' => 'localities', 'middleware' => 'role:administrator|moderator'], function () {
                Route::post('/create', 'Animal\AnimalLocalityController@postCreateLocality');
            });

            // Animal Species: Morph Combos
            Route::group(['prefix' => 'combos', 'middleware' => 'role:administrator|moderator'], function () {
                Route::post('/create', 'Animal\AnimalMorphComboController@postCreateMorphCombo');
            });

            // Animal Species: Morph Complexes
            Route::group(['prefix' => 'complexes', 'middleware' => 'role:administrator|moderator'], function () {
                Route::post('/create', 'Animal\AnimalMorphComplexController@postCreateMorphComplex');
            });
        });
    });

    // User Routes
    Route::group(['prefix' => 'users', 'middleware' => 'role:administrator'], function() {
        Route::get('/', 'User\UserController@index')->name('admin.users');
        Route::post('/fetch-all', 'User\UserController@postFetchAll');
        Route::post('/fetch', 'User\UserController@postFetch');
        Route::post('/update', 'User\UserController@postUpdate');

        // User Roles
        Route::group(['prefix' => 'roles'], function () {
            Route::get('/', 'User\UserRoleController@index')->name('admin.user.roles');
            Route::get('/create', 'User\UserRoleController@getCreate')->name('admin.user.roles.create');
            Route::post('/create', 'User\UserRoleController@postCreate');
        });

        // User Plans
        Route::group(['prefix' => 'plans'], function () {
            Route::get('/', 'User\UserPlanController@index')->name('admin.user.plans');
            Route::get('/create', 'User\UserPlanController@getCreate')->name('admin.user.plans.create');
            Route::post('/create', 'User\UserPlanController@postCreate');
        });

        // Invite Codes
        Route::group(['prefix' => 'codes'], function () {
            Route::get('/', 'User\UserCodeController@index')->name('admin.user.codes');
            Route::post('/fetch', 'User\UserCodeController@postFetch');
            Route::post('/create', 'User\UserCodeController@postCreate');
            Route::post('/update', 'User\UserCodeController@postUpdate');
            Route::post('/delete', 'User\UserCodeController@postDelete');
        });
    });
});

routes/dashboard.php
<?php

// Landing Page (excludes verify middleware)
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

// User Settings
Route::get('/settings', 'User\UserController@getSettings');
Route::post('/settings', 'User\UserController@postSettings');

// Animals
Route::group(['prefix' => 'animals'], function() {
    Route::get('/', 'Animal\AnimalController@index');
    Route::post('/fetch-all', 'Animal\AnimalController@postFetchAll');
    Route::post('/fetch', 'Animal\AnimalController@postFetch');
    Route::post('/create', 'Animal\AnimalController@postCreate');
});

routes/web.php
<?php

// Landing Page
Route::get('/', 'App\HomeController@index')->name('index');

// TOS / Privacy
Route::get('/tos', 'App\HomeController@tos');
Route::get('/privacy', 'App\HomeController@privacy');

// Calculator Routes
Route::get('calculator/{species?}/{parent1?}/{parent2?}', 'App\CalculatorController@index')->name('calculator');

// Article Routes
Route::get('articles', 'App\ArticleController@index')->name('articles');

// Almanac Routes
Route::get('almanac', 'App\AlmanacController@index')->name('almanac');
Route::get('almanac/{query}', 'App\AlmanacController@page')->name('almanac.page');

app/Models/User/User.php
<?php

namespace App\Models\User;

use Illuminate\Support\Facades\Config;
use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Events\UserAmended;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * Dispatches an event that clears the cache
     * @var array
     */
    protected $dispatchesEvents = [
        'saved'    => UserAmended::class,
        'deleted'  => UserAmended::class,
        'restored' => UserAmended::class,
    ];

    /**
     * The attributes that are mass assignable.
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Belongs to a user role.
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function role()
    {
        return $this->belongsTo('App\Models\User\UserRole', 'role_id');
    }

    /**
     * Has user settings
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function settings()
    {
        return $this->hasOne('App\Models\User\UserSetting');
    }

    /**
     * Belongs to user plan
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function plan()
    {
        return $this->belongsTo('App\Models\User\UserPlan');
    }

    /**
     * Check if a user is verified
     * @return bool
     */
    public function getIsVerifiedAttribute()
    {
        if ($this->settings->activation_token == null) return true;
        else return false;
    }

    /**
     * Check if user belongs to $role
     * @param array $roles
     * @return bool
     */
    public function hasRole(array $roles)
    {
        if (in_array(strtolower($this->role->name), $roles)) return true;
        else return false;
    }

    /**
     * Return the user's reputation rank
     * @return \Illuminate\Config\Repository|mixed
     */
    public function getReputationRankAttribute()
    {
        foreach (config('reputation') as $i => $rank) $amt[$i] = abs($i - $this->reputation);
        asort($amt);
        return config('reputation.' . $amt[0]);
    }
}

resources/views/layouts/partials/_alerts.blade.php
@if ($messages = Flash::flush())
    @foreach($messages as $message)
        @if(is_array($message['message']))
            @foreach($message['message'] as $m)
                <div class="alert {{ $message['type'] }} margin-10px">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ $m }}
                </div>
            @endforeach
        @else
            <div class="alert {{ $message['type'] }} margin-10px">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ $message['message'] }}
            </div>
        @endif
    @endforeach
@endif

@if(session('flash'))
    <p>{{ session('flash') }}</p>
@endif

resources/views/layouts/partials/_footer.blade.php
<div class="footer padding-x2">
	<div class="max">
		<div class="flex align-middle">
			<div class="width-4">
				&copy; <script>document.write(new Date().getFullYear())</script> | <a href="/tos">Terms of Service</a>
				| <a href="/privacy">Privacy Policy</a> | <a href="/contact">Contact</a>
			</div>
			<div class="width-4">
				<a href="/"><img class="block center" src="https://static.reptally.com/logo-bar-lt.png" alt="Reptally - Robust reptile tracking solution" width="100"/></a>
			</div>
			<div class="width-4 align-right">
				<span class="inline-block align-middle">Made with</span>
				<svg class="icon-heart fill-red-hover" title="I ♥ You Miranda" style="height: 1rem; width: 1rem;"><use xlink:href="#icon-heart"></use></svg>
			</div>
		</div>
	</div>
</div>

resources/views/layouts/partials/_nav.blade.php
@if (Auth::check())
    <div id="header" class="header shadow padding z-3 relative">
        <div class="max">
            <div class="flex nowrap padded align-middle">
                <div>
                    <a href="/"><img class="block" src="https://static.reptally.com/logo-bar-lt.png" alt="Reptally - Robust reptile tracking solution" width="200"/></a>
                </div>
                <div class="box">
                    <nav id="menuHeader1" class="menu horizontal">
                        <ul>
                            <li><a href="/almanac">Almanac</a></li>
                            <li><a href="/articles">Articles</a></li>
                            <li><a href="/calculator">Calculator</a></li>
                            <li><a href="/listings">Browse Animals</a></li>
                            <li><a href="/forums">Forums</a></li>
                        </ul>
                    </nav>
                </div>
                <div>
                    <nav id="menuHeader2" class="menu horizontal">
                        <ul>
                            @if(Auth::check())
                                <li>
                                    <div class="dropdown anchor-right tip-alt">
                                        <div class="profile-image">
                                            <img src="http://placehold.it/44x44" />
                                        </div>
                                        <div class="menu">
                                            <div class="bg-alt padding-x2 round-top">
                                                <div class="flex padded align-middle nowrap">
                                                    <div>
                                                        <div class="profile-image" style="width: 64px;">
                                                            <img src="http://placehold.it/64x64" />
                                                        </div>
                                                    </div>
                                                    <div>
                                                        <div class="flex flow-vertical">
                                                            <div class="h5">{{ Auth::user()->first_name }} {{ Auth::user()->last_name }}</div>
                                                            <div class="subtext">{{ Auth::user()->email }}</div>
                                                            <div class="subtext">{{ Auth::user()->reputation_rank }} ({{ Auth::user()->reputation }})</div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <ul>
                                                <li><a href="/dashboard">{!! $icon['gear'] !!}<span>Dashboard</span></a></li>
                                                <li><a href="/notifications">{!! $icon['gear'] !!}<span>Notifications</span></a></li>
                                                <li><a href="/settings">{!! $icon['gear'] !!}<span>Account Settings</span></a></li>
                                                <li><a href="/profile">{!! $icon['user'] !!}<span>Edit Profile</span></a></li>
                                                @if (Auth::user()->hasRole(['administrator', 'moderator']))
                                                    <li><a href="/admin">{!! $icon['user'] !!}<span>Admin Panel</span></a></li>
                                                @endif
                                                <li><hr></li>
                                                <li><a href="/logout">{!! $icon['logout'] !!}<span>Logout</span></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </li>
                            @else
                                <li><a href="/login">Login</a></li>
                                <li><a class="button" href="/register">Register</a></li>
                            @endif
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
@endif

resources/views/layouts/partials/_sidebar.blade.php
<div class="bg-alt z-2 relative shadow overflow-hidden">
    <div class="menu" id="menuSidebar">
        <ul>
            <li><a>{!! $icon['folder'] !!}<span>Animals</span>{!! $icon['chevron'] !!}</a>
                <ul>
                    <li><a href="/admin/animals">{!! $icon['folder'] !!}<span>Manage Animals</span></a></li>
                    <li><a href="/admin/listings">{!! $icon['folder'] !!}<span>Manage Listings</span></a></li>
                    <li><a href="/admin/racks">{!! $icon['folder'] !!}<span>Manage Racks</span></a></li>
                    <li><a href="/admin/incubator">{!! $icon['folder'] !!}<span>Incubator</span></a></li>
                    @if (Auth::user()->hasRole(['administrator'])) <li><a href="/admin/animals/species">{!! $icon['folder'] !!}<span>Species</span></a></li> @endif
                    @if (Auth::user()->hasRole(['administrator','moderator'])) <li><a href="/admin/animals/updates">{!! $icon['folder'] !!}<span>Species Change Requests</span></a></li> @endif
                </ul>
            </li>

            @if (Auth::user()->hasRole(['administrator']))
                <li><a>{!! $icon['users'] !!}<span>Users</span>{!! $icon['chevron'] !!}</a>
                    <ul>
                        <li><a href="/admin/users">{!! $icon['users'] !!}<span>Manage Users</span></a></li>
                        <li><a href="/admin/users/plans">{!! $icon['users'] !!}<span>Manage User Plans</span></a></li>
                        <li><a href="/admin/users/roles">{!! $icon['users'] !!}<span>Manage User Roles</span></a></li>
                        <li><a href="/admin/users/invoicing">{!! $icon['users'] !!}<span>Invoicing</span></a></li>
                    </ul>
                </li>
            @endif
            <li><a>{!! $icon['gear'] !!}<span>Settings</span>{!! $icon['chevron'] !!}</a>
                <ul>
                    <li><a><span>Settings 1</span></a></li>
                    <li><a><span>Settings 2</span></a></li>
                    <li><a><span>Settings 3</span></a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>